import{S as f,i as m}from"./assets/vendor-5b791d57.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{const u=document.querySelector(".searchForm"),a=document.querySelector(".searchInput"),l=document.querySelector(".loader"),n=document.querySelector(".gallery"),e="42055816-5ec499474650eadfc6b07a02f",s="https://pixabay.com/api/",i=new f(".gallery a");u.addEventListener("submit",d=>{d.preventDefault();const c=a.value.trim();if(c===""){m.error({title:"Error",position:"topRight",message:"Please enter a search term."});return}l.classList.remove("hidden"),n.innerHTML="",fetch(`${s}?key=${e}&q=${c}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(!t.ok)throw new Error(`HTTP error! Status: ${t.status}`);return t.json()}).then(t=>{if(t.hits.length===0)m.warning({title:"No Results",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});else{const r=t.hits.map(o=>({webformatURL:o.webformatURL,largeImageURL:o.largeImageURL,tags:o.tags,likes:o.likes,views:o.views,comments:o.comments,downloads:o.downloads}));p(r)}}).catch(t=>{console.error("Error fetching data:",t),m.error({title:"Error",position:"topRight",message:"An error occurred while fetching data. Please try again."})}).finally(()=>{l.classList.add("hidden")})});function p(d){const c=d.map((t,r)=>`
        <div class="gallery-item">
          <a href="${t.largeImageURL}" data-lightbox="gallery" data-title="${t.tags}">
            <img src="${t.webformatURL}" alt="${t.tags}" class="image-thumbnail image-${r+1}">
          </a>
          <div class="image-details image-details-${r+1}">
            <p class="likes likes-${r+1}">Likes: <span class="result-likes">${t.likes}</span></p>
            <p class="views views-${r+1}">Views: <span class="result-views">${t.views}</span></p>
            <p class="comments comments-${r+1}">Comments: <span class="result-comments">${t.comments}</span></p>
            <p class="downloads downloads-${r+1}">Downloads: <span class="result-downloads">${t.downloads}</span></p>
          </div>
        </div>
      `).join("");n.innerHTML=c,i.refresh()}});
//# sourceMappingURL=commonHelpers.js.map
